name: Build

on:
  push:
  pull_request:
    branches:
      - main
  workflow_call:
  workflow_run:
    workflows:
      - manual
    types:
      - requested

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      build: ${{ steps.filter.outputs.build }}
      code: ${{ steps.filter.outputs.code }}
    steps:
      - uses: actions/checkout@v7
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            build:
              - 'buildSrc/**'
              - 'gradle/**'
              - '*.gradle.kts'
              - 'gradle.properties'
            code:
              - 'src/**'
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: check-changes
    if: ${{ needs.check-changes.outputs.build == 'true' || needs.check-changes.outputs.code == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        run: ./gradlew build -S
